[workspace]
authors = ["ryan-moreno <rrmoreno@wisc.edu>"]
channels = ["conda-forge"]
name = "cuda-example"
platforms = ["osx-arm64", "linux-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.1,<3.14"

[feature.cpu.dependencies]
pytorch-cpu = ">=2.7.0,<3"

[feature.gpu.system-requirements]
cuda = "12"

[feature.gpu.target.linux-64.dependencies]
cuda-version = "12.9.*"
pytorch-gpu = ">=2.7.0,<3"

[environments]
cpu = ["cpu"]
gpu = ["gpu"]